
version: "3.9"
services:

  locking_chain:
    container_name: locking_chain
    image: legleux/rippled-xbridge
    command: "--conf /etc/opt/ripple/rippled.cfg -a"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/locking_chain:/etc/opt/ripple/
    ports:
      - 5005:5005
      - 6005:6005
      - 6006:6006
      - 51235:51235
    networks:
     xchain-net:
       ipv4_address: 10.0.0.2

  issuing_chain:
    container_name: issuing_chain
    image: legleux/rippled-xbridge
    command: "--conf /etc/opt/ripple/rippled.cfg -a"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/issuing_chain:/etc/opt/ripple/
    ports:
      - 5006:5006
      - 6007:6007
      - 6008:6008
      - 51236:51236
    networks:
      xchain-net:
        ipv4_address: 10.0.0.3

  witness0:
    container_name: witness0
    image: legleux/xbridge_witnessd
    command: "/opt/witness/witness.json"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/witness0:/opt/witness/
    ports:
      - "6010:6010"
    networks:
      xchain-net:
        ipv4_address: 10.0.0.4

  witness1:
    container_name: witness1
    image: legleux/xbridge_witnessd
    command: "/opt/witness/witness.json"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/witness1:/opt/witness/
    ports:
      - "6011:6011"
    networks:
      xchain-net:
        ipv4_address: 10.0.0.5

  witness2:
    container_name: witness2
    image: legleux/xbridge_witnessd
    command: "/opt/witness/witness.json"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/witness2:/opt/witness/
    ports:
      - "6012:6012"
    networks:
      xchain-net:
        ipv4_address: 10.0.0.6

  witness3:
    container_name: witness3
    image: legleux/xbridge_witnessd
    command: "/opt/witness/witness.json"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/witness3:/opt/witness/
    ports:
      - "6013:6013"
    networks:
      xchain-net:
        ipv4_address: 10.0.0.7

  witness4:
    container_name: witness4
    image: legleux/xbridge_witnessd
    command: "/opt/witness/witness.json"
    volumes:
      - ${XCHAIN_CONFIG_DIR}/witness4:/opt/witness/
    ports:
      - "6014:6014"
    networks:
      xchain-net:
        ipv4_address: 10.0.0.8

networks:
  xchain-net:
    name: xchain-net
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
