name: Lint and Type Check

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-type-check:
    name: Lint and type-check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load cached .local
        uses: actions/cache@v3
        with:
          path: /home/runner/.local
          key: dotlocal-3.11-${{ hashFiles('.github/workflows') }}

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python + Retrieve Poetry dependencies from cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'poetry'

      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"

      - name: Install poetry dependencies
        run: poetry install

      - name: Lint
        run: |
          poetry run flake8 sidechain_cli tests

      - name: Type-check
        run: |
          poetry run mypy --strict --implicit-reexport sidechain_cli
