name: Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  POETRY_VERSION: 1.4.2
  PYTHON_VERSION: "3.11"

jobs:
  lint-and-type-check:
    name: Lint and type-check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load cached .local
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: /home/runner/.local
          key: dotlocal-${{ env.POETRY_VERSION }}

      - name: Install poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org/ | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python + Retrieve Poetry dependencies from cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry"

      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"

      - name: Install poetry dependencies
        run: poetry install

      - name: Lint
        run: |
          poetry run flake8 xbridge_cli tests

      - name: Type-check
        run: |
          poetry run mypy --strict --implicit-reexport xbridge_cli
