name: Unit test

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-type-check:
    name: Lint and type-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"

      - name: Install poetry
        run: pipx install poetry

      - name: Retrieve poetry dependencies from cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'

      - name: Install poetry dependencies
        run: poetry install

      - name: Lint
        run: |
          poetry run flake8 sidechain_cli tests

      - name: Type-check
        run: |
          poetry run mypy --strict --implicit-reexport sidechain_cli
